import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";

export const metadata = {
  title: "Senri AI - AI Career Coach",
  description: "Generated by create next app",
  icon: "icon.png",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <head>
          <link rel="icon" href="/logo5.png" sizes="any" />

          {/* Google Analytics */}
          <script async src="https://www.googletagmanager.com/gtag/js?id=G-NNGSLBEB2L"></script>
          <script
            dangerouslySetInnerHTML={{
              __html: `
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', 'G-NNGSLBEB2L');
              `,
            }}
          />
        </head>

        {/* ✅ Inter-like system font */}
        <body className="font-sans">
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />

            <main className="min-h-screen">{children}</main>

            <Toaster richColors />

            <footer className="bg-muted/50 py-12">
              <p className="text-lg font-bold container mx-auto px-4 text-center text-gray-200">
                Made with ❤️ by senri
                <a
                  href="https://github.com/Vishal772-pixel"
                  className="text-yellow-400 hover:text-red-300"
                  target="_blank"
                >
                  {" "}
                  Team senri
                </a>
              </p>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}